print("hey")

text = "CFDQPCBODQLCYPULTJBBULURULXFDTXSCNTDZJBICLDQBTNDAUJBPOUJLGOCJLNCBTNDAUJBPOUJLLDDANCBTJPIDPPDFUELUPPXTQVVFQGMCBTCTDISCNNPLUPGOUTDQPDBPOUILCNNJBPOUNQBNDQBTCNVUUEJSUBPQEPDDQLLDDACBTKQTIUTJSDQVTPCMUCBCEAXNUVYJYDQBTPOCPNSUUPAJNNNDEOJCNPCBTJBIJBOULTDDLSOJGOSCNBUWPPDDQLNCBTNOUPDDMAUJBOULLDDACBTNOQPPOUTDDLRULXNDYPCBTCNMUTAUJYJVJMUTOULCBTJNCJTJTJTCBTNOUCNMUTAUJYJSDQVTTDNDAUPOJBIYDLOULCBTBDPPUVVCBXFDTXCBTJNCJTJSDQVTPOUBNOUNCJTNOUTYDLIDPOULPUNPCAUBPCBTVUYPJPJBPOUNUCPCPGOQLGOFUPSUUBPSDDPOULFDDMNCBTSDQVTJNVJEDQPHQJUPCBTIDPOULUCBTYUPGOJPPDOULCBTBDPNCXBDPOJBIPDBDFDTXJNCJTJSDQVTNDJNVJTDQPCBTNVJEEUTDYYQEPOULDCTCBTPOULUSCLBPCBXFDTXCPPOUGOQLGOUWGUEPACXFUCODIDLPSDYDLPOULUSCLBPCBXVDGMDBPOUTDDLCBTODINVJMUNCEQBGOUDBYVDDLJBNQAAULPJAUFUGCQNUJPNGDDVJYXDQBDPJGUADNPYDVMNTDBPIDPDGOQLGODBVXSOUBPOUXRUIDPPDFQPCODIJNTJYYULUBP"
count = 0
abc = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
res = ""
for letter in text:
    if letter == "G":
        count += 1
    
    if letter == "A":
        res += "F"  # 2.2%
    elif letter == "B":
        res += "O"  # 7.5%
    elif letter == "C":
        res += "I"  # 7%
    elif letter == "D":
        res += "T"  # 9.1%
    elif letter == "E":
        res += "B"  # 1.5%
    elif letter == "F":
        res += "B"  # 1.5%
    

    else:
        res += letter
    
print(count)
print(len(text))
print(float(count)/len(text)*100)
print(res)